from sys import argv
script,filename=argv
#filename="ex15sample.txt"
print(f" We are goint to earse {filename}")
print("If you what that hit cntrl-c")
print("If you don,t want hit return")
input("?")
print("opening the file")
tar=open(filename,'w')
print("truncating the file.Goodbye!")
tar.truncate()
print("now i am going to ask for 3 line")
l1=input("line1: ")
l2=input("line2: ")
l3=input("line3: ")
print("I am going to write those to the  files")
tar.write(l1)
tar.write("\n")
tar.write(l2)
tar.write("\n")
tar.write(l3)
tar.write("\n")
print("And finally to close it")
tar.close()